'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class notificaciones

    '''<summary>
    '''importantlink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents importantlink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''numImportantNotf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numImportantNotf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''fixeslink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fixeslink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''numFixesNotf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numFixesNotf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''upgradeslink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upgradeslink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''numUpgradesNotf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numUpgradesNotf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''historylink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents historylink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''numHistorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numHistorial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''notificationslist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notificationslist As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''importantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents importantes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''important control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents important As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''correcciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents correcciones As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''fixes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fixes As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''mejoras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mejoras As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''upgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upgrade As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''historial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents historial As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
