'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ARSD

    '''<summary>
    '''manageDocumentsLi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents manageDocumentsLi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''manageDocumentsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents manageDocumentsTab As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''historyDocumentsLi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents historyDocumentsLi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''historyDocumentsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents historyDocumentsTab As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''manageDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents manageDocuments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''estatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents estatus As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''subEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subEstatus As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''destinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents destinatario As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''actividades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actividades As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''actividadAsignada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actividadAsignada As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''estatusActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents estatusActividad As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''operador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operador As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvADTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvADTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''historyDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents historyDocuments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''actividadesTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actividadesTitulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''actividadDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actividadDescripcion As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''comentarioActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comentarioActividad As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''archivosActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivosActividad As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''verAdjuntos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents verAdjuntos As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''actualizarActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actualizarActividad As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''agregarActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents agregarActividad As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''cancelarActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cancelarActividad As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''usuariosActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuariosActividad As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''usuariosANotificar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuariosANotificar As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''confirmarRechazoActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmarRechazoActividad As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''confirmarFinalizarActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmarFinalizarActividad As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''cHDTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cHDTable As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvHDTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvHDTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''viewModalADCorrelativoRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewModalADCorrelativoRemitente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mvCorrelative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvCorrelative As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvDocumentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvDocumentType As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvStatus As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvSubStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSubStatus As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvSenderCorrelative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSenderCorrelative As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvReceiverCorrelative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvReceiverCorrelative As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvSenderUO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSenderUO As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvSenderCreatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSenderCreatedDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvSenderUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSenderUser As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvSenderRequiredDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSenderRequiredDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvReceiverUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvReceiverUser As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvReceiverDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvReceiverDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mvReceiverDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvReceiverDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''tbViewDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbViewDocument As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''archivosPrincipalesTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivosPrincipalesTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''addUserModalADCorrelativoRemitente2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addUserModalADCorrelativoRemitente2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''usuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuarios As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''taADComment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents taADComment1 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''btnADAsignar576 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnADAsignar576 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''uploadFileModalCorrelativoRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uploadFileModalCorrelativoRemitente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IDGrupoCoRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDGrupoCoRemitente As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''correlativoDeSalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents correlativoDeSalida As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''archivosSalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivosSalida As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''estatusSalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents estatusSalida As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''subEstatusSalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subEstatusSalida As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''archivosSalidaTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivosSalidaTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''confirmarArchivoSalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmarArchivoSalida As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''archivosTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivosTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''rechazar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rechazar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''rechazarActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rechazarActividad As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''finalizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents finalizar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''archivoSalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivoSalida As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''archivoActividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivoActividad As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''actualizarArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actualizarArchivo As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''eliminarArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eliminarArchivo As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''showFilesModalTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents showFilesModalTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''filecontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filecontent As Global.System.Web.UI.HtmlControls.HtmlIframe
End Class
