'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ID

    '''<summary>
    '''Tabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tipoDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tipoDocumento As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''correlativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents correlativo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''remitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents remitente As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''destinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents destinatario As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''fechaCreacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fechaCreacion As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''fechaRecibido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fechaRecibido As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''fechaRequerido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fechaRequerido As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''archivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents archivo As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''adjuntos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adjuntos As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descripcion As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''guardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guardar As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
